project_name: Default
working_dir: "."
cmd:
- bash run.sh
provisioning:
  gpu_type: h100
  gpu_count: 1
  cpu_count: 20
  ram: 160
  blank: false
teamcity:
  url: https://api.cadence.jetbrains.com
  build_conf_id: F9f81e71ac3a417cAa9d4af9ce6b7e84_JetTrain
env:
  variables: {}
  python:
    pip:
      requirements_path: requirements.txt
  secrets:
    variables: {}
    ssh_keys: []
  aws:
    sync_config: false
    sync_credentials: false
    sync_cache: false
project_sync:
  local:
    root: "."
    storage_name: Cadence Storage
    uri: ""
    exclude: []
    include: []
    sync_back: false
    snapshots: true
    storage_type: DEFAULT
inputs: []
outputs:
- type: OUTPUT
  storage_name: Cadence Storage
  uri: ""
  path: "."
  acceleration: false
  storage_type: DEFAULT
mounts: []
storages: []
description: resnet50
